# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Salsa
version:      0.01
version_from: lib/Mail/Salsa.pm
installdirs:  site
requires:
    Digest::MD5:                   2.33
    MIME::Base64:                  3.05
    MIME::Explode:                 0.37

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
